siteTitle = "全栈学院"
siteDescr = "在前端领域持续学习，不断精进"
siteAuthor = "王仕军"

twitterUrl = "https://twitter.com/wangshijun2010"
githubUrl = "https://github.com/wangshijun"
emailUrl = "mailto:wangshijun2010@gmail.com"
zhihuUrl = "https://www.zhihu.com/people/wangshijun"
juejinUrl = "https://juejin.im/user/57a7f634d342d300576b738d"
jianshuUrl = "http://www.jianshu.com/u/99b7dbb513a3"
segmentfaultUrl = "https://segmentfault.com/u/wangshijun2010"
wechatUrl = "http://mp.weixin.qq.com/mp/homepage?__biz=MjM5NTQ3MDEwMw==&hid=1&sn=4b514718d60ffd16d1caaf296ab00c66#wechat_redirect"

googleAnalyticsId = "UA-100066937-1"

linkPrefix = "/"
