siteTitle = "全栈学院"
siteDescr = "在前端领域不断精进，终身学习"
siteAuthor = "王仕军"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/wangshijun2010"
siteGithubUrl = "https://github.com/wangshijun"
siteEmailUrl = "mailto:wangshijun2010@gmail.com"
siteZhihuUrl = "https://www.zhihu.com/people/wangshijun"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
