siteTitle = "全栈学院"
siteDescr = "在前端领域不断精进，终身学习"
siteAuthor = "王仕军"

siteTwitterUrl = "https://twitter.com/wangshijun2010"
siteGithubUrl = "https://github.com/wangshijun"
siteEmailUrl = "wangshijun2010@gmail.com"
siteZhihuUrl = "https://www.zhihu.com/people/wangshijun"
siteJuejinUrl = "https://www.zhihu.com/people/wangshijun"
siteJianshuUrl = "https://www.zhihu.com/people/wangshijun"
siteSegmentfaultUrl = "https://www.zhihu.com/people/wangshijun"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
